include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
  errors:
    sort_child_properties_last: error
    always_put_required_named_parameters_first: error
    avoid_type_to_string: error

linter:
  rules:
    - camel_case_types
    - always_use_package_imports
    - avoid_returning_null_for_future
    - avoid_type_to_string
    - cancel_subscriptions
    - close_sinks
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_statements
    - always_put_required_named_parameters_first
    - avoid_annotating_with_dynamic
    - avoid_classes_with_only_static_members
    - avoid_double_and_int_checks
    - avoid_field_initializers_in_const_classes
    - avoid_final_parameters
    - avoid_multiple_declarations_per_line
    - avoid_positional_boolean_parameters
    - avoid_private_typedef_functions
    - avoid_returning_null
    - avoid_returning_this
    - avoid_setters_without_getters
    - avoid_types_on_closure_parameters
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - cascade_invocations
    - do_not_use_environment
    - eol_at_end_of_file
    - join_return_with_assignment
    - leading_newlines_in_multiline_strings
    - library_private_types_in_public_api
    - no_leading_underscores_for_library_prefixes
    - no_leading_underscores_for_local_identifiers
    - one_member_abstracts
    - parameter_assignments
    - prefer_expression_function_bodies
    - unnecessary_final
    - prefer_if_elements_to_conditional_expressions
    - prefer_interpolation_to_compose_strings
    - sized_box_shrink_expand
    - sort_unnamed_constructors_first
    - type_annotate_public_apis
    - sort_child_properties_last
    - unnecessary_late
    - unnecessary_null_aware_assignments
    - use_decorated_box
    - use_if_null_to_convert_nulls_to_bools
    - use_named_constants
    - use_setters_to_change_properties
    - use_string_buffers
    - always_declare_return_types